ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "project_type" text NOT NULL DEFAULT '';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "tagline" text NOT NULL DEFAULT '';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "short_description" text NOT NULL DEFAULT '';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "long_description" text NOT NULL DEFAULT '';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "address_text" text NOT NULL DEFAULT '';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "hero_title" text NOT NULL DEFAULT '';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "hero_subtitle" text NOT NULL DEFAULT '';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "hero_location_text" text NOT NULL DEFAULT '';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "primary_cta_label" text NOT NULL DEFAULT 'Découvrir le projet';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "secondary_cta_label" text NOT NULL DEFAULT 'Prendre rendez-vous';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "show_price" boolean NOT NULL DEFAULT true;
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "price_note" text NOT NULL DEFAULT '';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "secondary_image_url" text NOT NULL DEFAULT '';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "lifestyle_image_url" text NOT NULL DEFAULT '';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "project_section_title" text NOT NULL DEFAULT 'Le projet';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "project_section_description" text NOT NULL DEFAULT '';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "lifestyle_title" text NOT NULL DEFAULT '';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "lifestyle_description" text NOT NULL DEFAULT '';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "location_section_title" text NOT NULL DEFAULT 'Emplacement';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "location_description" text NOT NULL DEFAULT '';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "location_advantages" text[] NOT NULL DEFAULT '{}';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "map_embed_url" text NOT NULL DEFAULT '';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "map_share_url" text NOT NULL DEFAULT '';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "contact_title" text NOT NULL DEFAULT 'Intéressé par ce projet ?';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "contact_subtitle" text NOT NULL DEFAULT 'Notre équipe vous recontacte dans les 24 heures pour organiser une visite ou répondre à toutes vos questions.';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "meta_title" text NOT NULL DEFAULT '';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "meta_description" text NOT NULL DEFAULT '';
